services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    depends_on:
      - rabbitmq
      - mssql
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    hostname: rabbitmq

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pa55w0rd! 


  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686