// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Inventory.Repositories;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Inventory.Repositories.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("products")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Inventory.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items", "products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("111f9883-4b53-41eb-bcc3-8f4e6f29edf6"),
                            Name = "Monitor",
                            Price = 119.98999999999999,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("bdabc506-3cac-47bf-b30b-a175e53cedfe"),
                            Name = "Laptop",
                            Price = 499.99000000000001,
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("e9386ab6-6a40-4fdf-876b-8efa7a3d30f0"),
                            Name = "Keyboard",
                            Price = 11.99,
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("14e92630-424a-4fd3-8657-4e56da9baf6b"),
                            Name = "Mouse",
                            Price = 7.9900000000000002,
                            Quantity = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
